import stylesModule from "./styles.module.css"

export const sizeStyles = {
  sm: {
    text: "text-sm font-base",
    padding: "pl-4 pr-[2px] py-[2px]",
    iconSize: "w-10 h-10",
    iconContainer: "w-10 h-10 ml-4",
    icon: "w-5 h-5",
    fontSize: "text-[14px]",
    clipPathClass: stylesModule.sm,
    borderRadiusClass: stylesModule.sm,
    iconClipPathClass: stylesModule.smIcon,
    iconBorderRadiusClass: stylesModule.smIcon,
  },
  md: {
    text: "text-base font-base",
    padding: "pl-6 pr-[2px] py-[2px]",
    iconSize: "w-12 h-12",
    iconContainer: "w-12 h-12 ml-6",
    icon: "w-6 h-6",
    fontSize: "text-[16px]",
    clipPathClass: stylesModule.md,
    borderRadiusClass: stylesModule.md,
    iconClipPathClass: stylesModule.mdIcon,
    iconBorderRadiusClass: stylesModule.mdIcon,
  },
  lg: {
    text: "text-lg font-semibold",
    padding: "pl-8 pr-[2px] py-[2px]",
    iconSize: "w-14 h-14",
    iconContainer: "w-14 h-14 ml-8",
    icon: "w-7 h-7",
    fontSize: "text-[18px]",
    clipPathClass: stylesModule.lg,
    borderRadiusClass: stylesModule.lg,
    iconClipPathClass: stylesModule.lgIcon,
    iconBorderRadiusClass: stylesModule.lgIcon,
  },
  xl: {
    text: "text-xl font-semibold",
    padding: "pl-10 pr-[2px] py-[2px]",
    iconSize: "w-16 h-16",
    iconContainer: "w-16 h-16 ml-10",
    icon: "w-8 h-8",
    fontSize: "text-[20px]",
    clipPathClass: stylesModule.xl,
    borderRadiusClass: stylesModule.xl,
    iconClipPathClass: stylesModule.xlIcon,
    iconBorderRadiusClass: stylesModule.xlIcon,
  },
  "2xl": {
    text: "text-2xl font-bold",
    padding: "pl-12 pr-[2px] py-[2px]",
    iconSize: "w-20 h-20",
    iconContainer: "w-20 h-20 ml-12",
    icon: "w-10 h-10",
    fontSize: "text-[24px]",
    clipPathClass: stylesModule.size2xl,
    borderRadiusClass: stylesModule.size2xl,
    iconClipPathClass: stylesModule.size2xlIcon,
    iconBorderRadiusClass: stylesModule.size2xlIcon,
  },
}
